### ISSUE TITLE
Flask(5000) -> ./best_model.h5을 찾을 수 없다는 이슈

### ISSUE THREAD

**Issue by snghyun331** [snghyun331/elice-damchae-upgrade#11]
![화면 캡처 2023-10-20 014447](https://github.com/snghyun331/elice-damchae-upgrade/assets/108854903/961ec314-258d-40c3-a7b3-3702b78a8827)

**Comment by snghyun331** [comment]
### 해결방법
docker compose를 아래와 같이 설정했기 때문에
```
kobert:
    image: "snghyun/kobert2"
    container_name: "kobert"
    volumes:
      - ./back:/app/back
    command: python /app/back/src/ai/app.py
    ports:
      - "5000:5000"
```
경로를 **컨테이너 내부**로 맞춰야해서 `./`경로가 아닌 `/app/back/src/ai`경로로 수정해야한다.
